[package]
name = "rust-practice"
version = "0.1.0"
authors = ["zhouzibo <18208965365@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ch3 = {path = "./ch3"}
